# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce127b0f4c9361ceb98b8b6aa08f2db581bfe0c3b5d98ff4cab29cc08ce1ac3f85a3af2cec1c779a5b9bbdfd0b483562fb43d99d3228094a038554565e47cabc

test:
  secret_key_base: ae333ec78986064e18f0a213e76c71e2c52c0a20f21c153c74ea9161b28411a48e0d2566461c82c86793fdfcd6ab3775062a7f90dbd0cdfa29aada310a6a8af9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
